#!/bin/bash

NAME="purbeurre"
DIR=/home/etiennody/purbeurre
USER=etiennody
GROUP=etiennody
WORKERS=3
BIND=unix:/home/etiennody/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=purbeurre_project.settings.prod
DJANGO_WSGI_MODULE=purbeurre_project.wsgi
LOG_LEVEL=error

cd $DIR
source /home/etiennody/.local/share/virtualenvs/purbeurre-xPbW4kZb/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec /home/etiennody/.local/share/virtualenvs/purbeurre-xPbW4kZb/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
