# Generated by Django 3.1 on 2020-08-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200814_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_score',
        ),
    ]
